### ISSUE TITLE
 Error uploading file to Google Cloud Storage: error:0909006C:PEM routines:get_name:no start line

### ISSUE THREAD

**Issue by nickimola** [strapi-community/strapi-provider-upload-google-cloud-storage#116]
Hi

I've followed the tutorial on how to setup the configuration outside GCP.
I have setup all in strapi (config/prod/plugins.js as per documentation) as well as included the ENVs inside heroku (and they are used correctly - or so it seams).

The app compiles and everything runs, but when I try to upload a file, I get this error:

```
2021-12-29T08:40:38.772237+00:00 app[web.1]: Error uploading file to Google Cloud Storage: error:0909006C:PEM routines:get_name:no start line
2021-12-29T08:40:38.772799+00:00 app[web.1]: [2021-12-29 08:40:38.772] error: error:0909006C:PEM routines:get_name:no start line
2021-12-29T08:40:38.772800+00:00 app[web.1]: Error: error:0909006C:PEM routines:get_name:no start line
2021-12-29T08:40:38.772800+00:00 app[web.1]: at Sign.sign (node:internal/crypto/sig:131:29)
2021-12-29T08:40:38.772800+00:00 app[web.1]: at Object.sign (/app/node_modules/jwa/index.js:152:45)
2021-12-29T08:40:38.772801+00:00 app[web.1]: at Object.jwsSign [as sign] (/app/node_modules/jws/lib/sign-stream.js:32:24)
2021-12-29T08:40:38.772801+00:00 app[web.1]: at GoogleToken.requestToken (/app/node_modules/gtoken/build/src/index.js:225:31)
2021-12-29T08:40:38.772801+00:00 app[web.1]: at GoogleToken.getTokenAsyncInner (/app/node_modules/gtoken/build/src/index.js:163:21)
2021-12-29T08:40:38.772802+00:00 app[web.1]: at GoogleToken.getTokenAsync (/app/node_modules/gtoken/build/src/index.js:142:55)
2021-12-29T08:40:38.772802+00:00 app[web.1]: at GoogleToken.getToken (/app/node_modules/gtoken/build/src/index.js:94:21)
2021-12-29T08:40:38.772803+00:00 app[web.1]: at JWT.refreshTokenNoCache (/app/node_modules/google-auth-library/build/src/auth/jwtclient.js:171:36)
2021-12-29T08:40:38.772803+00:00 app[web.1]: at JWT.refreshToken (/app/node_modules/google-auth-library/build/src/auth/oauth2client.js:152:24)
2021-12-29T08:40:38.772808+00:00 app[web.1]: at JWT.getRequestMetadataAsync (/app/node_modules/google-auth-library/build/src/auth/oauth2client.js:284:28)
2021-12-29T08:40:38.772808+00:00 app[web.1]: at JWT.getRequestMetadataAsync (/app/node_modules/google-auth-library/build/src/auth/jwtclient.js:94:26)
2021-12-29T08:40:38.772813+00:00 app[web.1]: at JWT.getRequestHeaders (/app/node_modules/google-auth-library/build/src/auth/oauth2client.js:247:37)
2021-12-29T08:40:38.772814+00:00 app[web.1]: at GoogleAuth.authorizeRequest (/app/node_modules/google-auth-library/build/src/auth/googleauth.js:600:38)
2021-12-29T08:40:38.772814+00:00 app[web.1]: at async Promise.all (index 1)
```

Can you help me with this please? I searched online but couldn't find anything about this.

Thanks in advance

**Comment by Lith** [comment]
Hi @nickimola,

I suggest you to setup again this part : 
- [Setting up Google authentication](https://github.com/Lith/strapi-provider-upload-google-cloud-storage#-setting-up-google-authentication)

Which release of Strapi are you using ? 
- V3 or V4 ?

Please give us as more as possible information about your environment, this can happen too with a bad version of NPM or Node.

Thanks :)

**Comment by lulumahot** [comment]
Hi @nickimola,
Facing the same issue in V4, I found a solution on the web.
You need to sanitize the private key in config/plugins.js :
`"private_key": env('GCS_PRIVATE_KEY').replace(/\\n/g, '\n'),`
