### ISSUE TITLE
Could not load upload provider "strapi-provider-upload-google-cloud-storage"

### ISSUE THREAD

**Issue by piro92** [strapi-community/strapi-provider-upload-google-cloud-storage#128]
**Describe the bug**
After deploying strapi project to gCloud it can't find the provider. (Whole app crashes)

Error: Could not load upload provider "strapi-provider-upload-google-cloud-storage".
    at createProvider (/workspace/node_modules/@strapi/plugin-upload/server/bootstrap.js:47:11)
    at Object.module.exports [as bootstrap] (/workspace/node_modules/@strapi/plugin-upload/server/bootstrap.js:9:38)
at Object.bootstrap (/workspace/node_modules/@strapi/strapi/lib/core/domain/module/index.js:40:47)
    at Object.bootstrap (/workspace/node_modules/@strapi/strapi/lib/core/registries/modules.js:28:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Strapi.runLifecyclesFunctions (/workspace/node_modules/@strapi/strapi/lib/Strapi.js:468:5)
    at async Strapi.bootstrap (/workspace/node_modules/@strapi/strapi/lib/Strapi.js:406:5)
    at async Strapi.load (/workspace/node_modules/@strapi/strapi/lib/Strapi.js:415:5)
    at async Strapi.start (/workspace/node_modules/@strapi/strapi/lib/Strapi.js:163:9)

**To Reproduce**
package.json dependencies
    "@strapi-community/strapi-provider-upload-google-cloud-storage": "^4.1.7",
    "@strapi/plugin-i18n": "4.1.6",
    "@strapi/plugin-users-permissions": "4.1.6",
    "@strapi/strapi": "4.1.6",

cms-strapi/config/plugins.js
```
module.exports = ({ env }) => ({
  upload: {
    config: {
      provider: "strapi-provider-upload-google-cloud-storage",
      providerOptions: {
        bucketName: "myBucket",
        publicFiles: false,
        uniform: false,
        basePath: "",
      },
    },
  },
  publisher: {
    enabled: true,
  },
});
```

**Expected behavior**
Gcloud storage works

**Comment by philhack** [comment]
Changing the provider from:
```
provider: 'strapi-provider-upload-google-cloud-storage',
```

to

```
provider: '@strapi-community/strapi-provider-upload-google-cloud-storage',
```
should fix this for you.

**Comment by piro92** [comment]
That works, thanks!

**Comment by websmith** [comment]
Just FYI, the provider name is still using the old name in the NPM docs 😬 
https://www.npmjs.com/package/@strapi-community/strapi-provider-upload-google-cloud-storage

Can this be updated as well?
